game.splash("게임 이름")
story.printText("7954 AD", 80, 50, 1, 15, story.TextSpeed.Fast)
story.printText("Earth's ozone layer", 80, 50, 1, 15, story.TextSpeed.Fast)
story.printText("was destroyed", 80, 50, 1, 15, story.TextSpeed.Slow)
scene.setBackgroundImage(assets.image`게임 배경`)
while (!(controller.A.isPressed())) {
    pause(100)
}
tiles.setCurrentTilemap(tilemap`맵`)
let 지구파견로봇 = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
controller.moveSprite(지구파견로봇)
