sprites.onOverlap(SpriteKind.Player, SpriteKind.Food, function (sprite, otherSprite) {
    story.spriteMoveToLocation(mySprite, 320, 8, 100)
})
let mySprite: Sprite = null
let 지구파견로봇: Sprite = null
game.splash("게임 이름")
story.printText("7954 AD", 80, 50, 1, 15, story.TextSpeed.Fast)
story.printText("Earth's ozone layer", 80, 50, 1, 15, story.TextSpeed.Fast)
story.printText("was destroyed", 80, 50, 1, 15, story.TextSpeed.Slow)
scene.cameraFollowSprite(지구파견로봇)
scene.setBackgroundImage(assets.image`게임 배경`)
pause(2000)
tiles.setCurrentTilemap(tilemap`맵`)
지구파견로봇 = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
지구파견로봇.setPosition(2, 60)
controller.moveSprite(지구파견로봇)
mySprite = sprites.create(img`
    ........................
    .....ffff...............
    ...fff22fff.............
    ..fff2222fff............
    .fffeeeeeefff...........
    .ffe222222eef...........
    .fe2ffffff2ef...........
    .ffffeeeeffff...........
    ffefbf44fbfeff..........
    fee41fddf14eef..........
    .ffffdddddeef...........
    fddddf444eef............
    fbbbbf2222f4e...........
    fbbbbf2222fd4...........
    .fccf45544f44...........
    ..ffffffff..............
    ....ff..ff..............
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Food)
mySprite.setPosition(160, 8)
